version: "3"
services:
  node-app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules #to avoid errors if remove node_modules directory in hostdocker build -t node-app-image
    env_file: .env
    #environments:
      #- PORT=3000